### ISSUE TITLE
Getting error while running yarn run smartAccount address

### ISSUE THREAD

**Issue by tomarsachin2271** [bcnmy/sdk-examples#32]
While setting this repo i run into below error while running the command `yarn run smartAccount address`

```
$ ts-node scripts/index.ts address
/Users/sachintomar/github/sdk-examples/backend-node/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/gasless/parallelUserOpsMintNFT.ts:18:37 - error TS2339: Property 'numOfParallelUserOps' does not exist on type '{ privateKey: string; accountIndex: number; chainId: number; rpcUrl: string; bundlerUrl: string; biconomyPaymasterUrl: string; preferredToken: string; tokenList: never[]; }'.

18 const numOfParallelUserOps = config.numOfParallelUserOps;
                                       ~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/sachintomar/github/sdk-examples/backend-node/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/sachintomar/github/sdk-examples/backend-node/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/sachintomar/github/sdk-examples/backend-node/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/sachintomar/github/sdk-examples/backend-node/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/sachintomar/github/sdk-examples/backend-node/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/sachintomar/github/sdk-examples/backend-node/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Function.Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19) {
  diagnosticCodes: [ 2339 ]
}
error Command failed with exit code 1.
```

### Reproduction steps
1. Git clone repository
2. Go to backend-node folder
3. Run `yarn`
4. Run `yarn run smartAccount init --network=arbitrum-one-mainnet`
5. Run `yarn run smartAccount address`

**Comment by livingrockrises** [comment]
I will create PR mentioning this issue

**Comment by livingrockrises** [comment]
> I will create PR mentioning this issue

https://github.com/bcnmy/sdk-examples/pull/34
@tomarsachin2271
